[package]
name = "hp-client"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
# Телефон работает только в P2P-режиме.
connection = { path = "../connection", default-features = false, features = ["p2p"] }
hp-tun = { path = "../tun" }
